// app/modules/[slug]/page.tsx
import { notFound } from "next/navigation";

import { Section, Grid } from "@/components/layout/Section";
import { Card, CardHeader } from "@/components/ui/Card";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { LinkButton } from "@/components/ui/Button";
import { KpiRow } from "@/components/ui/KpiRow";

import { getModule } from "@/lib/modules";

const EMAIL = "contact@ecoveraz.com";
const MAILTO = `mailto:${EMAIL}?subject=${encodeURIComponent(
  "EcoVeraZ — Module Inquiry"
)}`;

function ToneBadge({
  tone,
  text,
}: {
  tone?: "good" | "neutral" | "warn";
  text: string;
}) {
  return (
    <StatusBadge tone={tone ?? "neutral"} mono>
      {text}
    </StatusBadge>
  );
}

export default function ModulePage({ params }: { params: { slug: string } }) {
  const mod = getModule(params.slug);
  if (!mod) return notFound();

  return (
    <>
      {/* HERO */}
      <Section size="lg">
        <Grid>
          <div className="md:col-span-8">
            <div className="flex items-center gap-2">
              <StatusBadge tone="neutral" mono>
                {mod.statusLabel}
              </StatusBadge>
              <StatusBadge tone="neutral" mono>
                REVIEW LAYER
              </StatusBadge>
            </div>

            <h1 className="mt-4 text-3xl font-semibold tracking-tight">
              {mod.title}
            </h1>

            <p className="mt-3 text-sm text-text-300 leading-relaxed">
              {mod.tagline}
            </p>

            <div className="mt-6 flex flex-wrap gap-3">
              <LinkButton href="/trust-core" variant="primary">
                Trust Core
              </LinkButton>
              <LinkButton href="/platform" variant="secondary">
                Back to Platform
              </LinkButton>
            </div>

            <div className="mt-5 rounded-xl border border-border bg-surface-2 px-4 py-3">
              <div className="text-xs font-medium text-text-400">Boundary</div>
              <p className="mt-1 text-xs text-text-400 leading-relaxed">
                EcoVeraZ operates strictly at the evidence and review layer. This
                module describes review-ready artifacts and signals. It does not
                certify, approve, score, or determine compliance or outcomes.
              </p>
            </div>
          </div>

          {/* POSTURE */}
          <div className="md:col-span-4">
            <Card>
              <CardHeader
                title="Evidence posture"
                subtitle="How this module is safe to use in reviews"
              />
              <KpiRow label="Exposure" value="Public-safe artifacts" mono />
              <KpiRow label="Internals" value="Not exposed" mono />
              <KpiRow label="Outputs" value="Evidence artifacts" mono />
              <KpiRow label="Interpretation" value="External reviewer" mono />
            </Card>
          </div>
        </Grid>
      </Section>

      {/* WHAT IT PRODUCES */}
      <Section
        size="lg"
        title="What it produces"
        subtitle="Evidence artifacts generated by this module"
      >
        <Grid>
          <div className="md:col-span-12">
            <Card>
              <div className="grid gap-3">
                {mod.outcomes.map((o) => (
                  <div key={o} className="flex gap-3">
                    <div className="mt-1.5 h-2 w-2 rounded-full bg-accent-400" />
                    <div className="text-sm text-text-200 leading-relaxed">
                      {o}
                    </div>
                  </div>
                ))}
              </div>

              <div className="mt-4 text-xs text-text-400">
                These are evidence artifacts for review. They are not compliance
                results or performance claims.
              </div>
            </Card>
          </div>
        </Grid>
      </Section>

      {/* WHERE IT APPEARS */}
      <Section
        size="lg"
        title="Where it appears"
        subtitle="Surfaces that consume this module’s outputs"
      >
        <Grid>
          <div className="md:col-span-12 grid gap-6 md:grid-cols-3">
            {mod.appearsIn.map((s) => (
              <Card key={s}>
                <CardHeader title={s} subtitle="Review surface" />
                <p className="text-sm text-text-300 leading-relaxed">
                  Presented as traceable evidence with explicit boundaries and
                  references.
                </p>
              </Card>
            ))}
          </div>
        </Grid>
      </Section>

      {/* REVIEW SIGNALS */}
      <Section
        size="lg"
        title="Review signals"
        subtitle="High-signal indicators of evidence readiness and integrity"
      >
        <Grid>
          <div className="md:col-span-12 grid gap-6 md:grid-cols-3">
            {mod.signals.map((s) => (
              <Card key={s.label}>
                <CardHeader title={s.label} subtitle="Evidence signal" />
                <div className="mt-2 flex justify-between">
                  <span className="text-sm text-text-300">State</span>
                  <ToneBadge tone={s.tone} text={s.value} />
                </div>
                <p className="mt-3 text-xs text-text-400">
                  Indicates evidence condition only — not regulatory acceptance.
                </p>
              </Card>
            ))}
          </div>
        </Grid>
      </Section>

      {/* SAMPLE OUTPUT */}
      <Section
        size="lg"
        title="Example output"
        subtitle="Illustrative evidence artifact preview"
      >
        <Grid>
          <div className="md:col-span-12">
            <Card dense>
              <CardHeader
                title={mod.sampleOutputTitle}
                subtitle="Illustrative only"
                right={
                  <StatusBadge tone="neutral" mono>
                    SAMPLE
                  </StatusBadge>
                }
              />

              <div className="rounded-md border border-border bg-bg-850 p-4">
                <div className="evz-mono space-y-2 text-xs text-text-200">
                  {mod.sampleOutputLines.map((l) => (
                    <div key={l}>• {l}</div>
                  ))}
                </div>
              </div>

              <p className="mt-3 text-xs text-text-400">
                This preview demonstrates structure and traceability only. It is
                not a compliance or outcome statement.
              </p>
            </Card>
          </div>
        </Grid>
      </Section>

      {/* CTA */}
      <Section size="lg">
        <Card>
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div>
              <div className="text-base font-semibold">
                Review this module in context
              </div>
              <p className="mt-1 text-sm text-text-300">
                Walk through evidence artifacts, review posture, and verification
                surfaces — without outcome claims.
              </p>
            </div>

            <div className="flex gap-2">
              <LinkButton href={MAILTO} variant="secondary">
                Email EcoVeraZ
              </LinkButton>
              <LinkButton href="/trust-core" variant="primary">
                Trust Core
              </LinkButton>
            </div>
          </div>

          <p className="mt-4 text-xs text-text-400">
            Reminder: EcoVeraZ provides evidence infrastructure. External parties
            determine conclusions.
          </p>
        </Card>
      </Section>
    </>
  );
}
